# Generated by Django 4.1 on 2022-09-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_picture'),
        ('posts', '0002_post_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='accounts.profile'),
        ),
    ]
